---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dawarich-secrets
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_ISSUER: "{{ .OIDC_ISSUER }}"
        OIDC_REDIRECT_URI: "{{ .OIDC_REDIRECT_URI }}"
        GEOAPIFY_API_KEY: "{{ .GEOAPIFY_API_KEY }}"
        SMTP_DOMAIN: "{{ .SMTP_DOMAIN }}"
        SMTP_FROM: "{{ .SMTP_FROM }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_SERVER: "{{ .SMTP_SERVER }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
  dataFrom:
    - extract:
        key: dawarich-secrets
    - extract:
        key: protonmail-smtp
