apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oidc-secret
    template:
      data:
        OIDC_API_URL: "{{ .OIDC_API_URL }}"
        OIDC_AUTH_URL: "{{ .OIDC_AUTH_URL }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_SIGNOUT_URL: "{{ .OIDC_SIGNOUT_URL }}"
        OIDC_TOKEN_URL: "{{ .OIDC_TOKEN_URL }}"
  dataFrom:
    - extract:
        key: pocket-id-grafana
