apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-auth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dragonfly-auth-secret
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
  dataFrom:
    - extract:
        key: authelia-dragonfly-secret
