apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tuppr
    repo: oci://ghcr.io/home-operations/charts
    version: 0.0.43
    releaseName: tuppr
    namespace: system-upgrade
    valuesFile: values.yaml
