apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app jellyfin

resources:
  - namespace.yaml
  - backend-traffic-policy.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    namespace: *app
    releaseName: *app
    valuesFile: values.yaml
  - name: pvc-backup
    repo: https://smauermann.github.io/helm-charts
    version: 2.2.1
    releaseName: jellyfin-backup
    valuesInline:
      appName: *app
      backup:
        pvcName: jellyfin-config
      restore:
        enabled: true
        pvcSize: 10Gi
