apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: garage-config
    files:
      - config/configuration.toml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - secrets.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    releaseName: garage
    namespace: garage
    valuesFile: values.yaml
