---
# HTTPRoute for Tempo query frontend (Grafana access)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tempo-query
  namespace: tempo
  annotations:
    gethomepage.dev/description: Distributed Tracing
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: grafana-tempo.png
    gethomepage.dev/name: Tempo
spec:
  hostnames:
    - tempo.costanza.cloud
  parentRefs:
    - kind: Gateway
      name: private
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: tempo
          namespace: tempo
          port: 3100
