apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.5.0
    namespace: arr
    releaseName: jellyseerr
    valuesFile: values.yaml
  - name: pvc-backup
    repo: https://smauermann.github.io/helm-charts
    version: 2.2.0
    releaseName: jellyseerr-backup
    valuesInline:
      appName: jellyseerr
      backup:
        pvcName: jellyseerr-config
      restore:
        enabled: true
        pvcSize: 5Gi
