apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-app-credentials
    template:
      type: Opaque
      data:
        github_app_id: "{{ .github_app_id }}"
        github_app_installation_id: "{{ .github_app_installation_id }}"
        github_app_private_key: "{{ .github_app_private_key }}"
  dataFrom:
    - extract:
        key: github-app-credentials
