apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    namespace: arr
    releaseName: sonarr
    valuesFile: values.yaml
  - name: pvc-backup
    repo: https://smauermann.github.io/helm-charts
    version: 2.2.1
    releaseName: sonarr-backup
    namespace: arr
    valuesInline:
      appName: sonarr
      backup:
        pvcName: sonarr-config
      restore:
        enabled: true
        pvcSize: 5Gi
