apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app calibre-web

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.5.0
    namespace: *app
    releaseName: *app
    valuesFile: values.yaml
  - name: pvc-backup
    repo: https://smauermann.github.io/helm-charts
    version: 2.2.1
    releaseName: calibre-web-backup
    valuesInline:
      appName: *app
      backup:
        pvcName: calibre-web-config
      restore:
        enabled: true
        pvcSize: 5Gi
