apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts/
    version: 2.2.1
    releaseName: onepassword-connect
    namespace: external-secrets
    includeCRDs: false
    valuesFile: values.yaml
