apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &project arr
  namespace: argocd
  labels:
    cloud.costanza: *project
spec:
  generators:
    - git:
        repoURL: https://github.com/smauermann/homelab
        revision: main
        directories:
          - path: kubernetes/applications/media/arr/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        cloud.costanza: *project
    spec:
      project: *project
      source:
        repoURL: https://github.com/smauermann/homelab
        targetRevision: main
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
