apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-secrets
  namespace: arr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: arr-secrets
    template:
      engineVersion: v2
      type: Opaque
      data:
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR__AUTH__APIKEY }}"
        RADARR__AUTH__APIKEY: "{{ .RADARR__AUTH__APIKEY }}"
        SONARR__AUTH__APIKEY: "{{ .SONARR__AUTH__APIKEY }}"
  dataFrom:
    - extract:
        key: arr-secrets
