apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-set.yaml
  - namespace.yaml
  - arr-secrets.yaml

configMapGenerator:
  - name: common-env
    literals:
      - TZ="Europe/Berlin"
