apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oidc-secret
    template:
      data:
        client-id: '{{ index . "client-id" }}'
        client-secret: '{{ index . "client-secret" }}'
  dataFrom:
    - extract:
        key: pocket-id-miniflux
