apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-github-homelab
  labels:
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-repo-github-homelab
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
        type: "{{ .type }}"
        url: "{{ .url }}"
        username: "{{ .username }}"
  dataFrom:
    - extract:
        key: github-argocd-creds
