# Merges the bcrypt hash into argocd-secret for account authentication
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-github-actions
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: accounts.githubActions.password
      remoteRef:
        key: argocd-github-actions
        property: passwordHash

