apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-github-homelab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-repo-github-homelab
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
          app.kubernetes.io/part-of: argocd
      data:
        type: "{{ .type }}"
        url: "{{ .url }}"
        username: "{{ .username }}"
  dataFrom:
    - extract:
        key: github-argocd-creds
