apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-github-webhook-secret
    template:
      type: Opaque
      data:
        credential: "{{ .credential }}"
  dataFrom:
    - extract:
        key: argocd-github-webhook-secret
