apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-github-webhook-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        credential: "{{ .credential }}"
  dataFrom:
    - extract:
        key: argocd-github-webhook-secret
