---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-collector

resources:
  - namespace.yaml
  - route.yaml

helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.146.1
    releaseName: otel-collector
    namespace: otel-collector
    includeCRDs: true
    valuesFile: values.yaml
