---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-logs

resources:
  - namespace.yaml
  - route.yaml

helmCharts:
  - name: victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.9.1
    releaseName: victoria-logs
    namespace: victoria-logs
    includeCRDs: true
    valuesFile: values.yaml
