---
# HTTPRoute for VictoriaLogs UI and API
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-logs
  namespace: victoria-logs
  annotations:
    gethomepage.dev/description: Log Aggregation
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: victoriametrics.png
    gethomepage.dev/name: VictoriaLogs
spec:
  hostnames:
    - vlogs.costanza.cloud
  parentRefs:
    - kind: Gateway
      name: private
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: victoria-logs-victoria-logs-single-server
          namespace: victoria-logs
          port: 9428
