apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudnative-pg
    releaseName: cloudnative-pg-operator
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.1
    namespace: cnpg-system
    includeCRDs: true
    valuesFile: values.yaml
