apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dawarich-backup
spec:
  method: plugin
  immediate: true
  # backup 1:30 am daily, note the additional setting for seconds
  schedule: "0 30 1 * * *"
  backupOwnerReference: self
  cluster:
    name: dawarich-postgres
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
