apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-admin
    template:
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
  dataFrom:
    - extract:
        key: miniflux-admin
