apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
spec:
  configuration:
    destinationPath: s3://barman-backups/
    endpointURL: https://s3.costanza.cloud
    s3Credentials:
      accessKeyId:
        name: garage-store
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-store
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
