apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguard-users
    template:
      data:
        users.yaml: '{{ index . "users.yaml" }}'
  dataFrom:
    - extract:
        key: adguard-users
