apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    releaseName: iperf
    namespace: iperf
    valuesFile: values.yaml
