apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tunnel-credentials
    template:
      data:
        credentials.json: '{{ index . "credentials.json" }}'
  dataFrom:
    - extract:
        key: cloudflare-tunnel-credentials
