apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
spec:
  method: plugin
  immediate: true
  # backup 1:30 am daily, note the additional setting for seconds
  schedule: "0 30 1 * * *"
  backupOwnerReference: self
  cluster:
    name: PLACEHOLDER
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

