apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - objectstore.yaml
  - secrets.yaml
  - backup.yaml

replacements:
  - source:
      kind: Cluster
      group: postgresql.cnpg.io
      version: v1
      fieldPath: metadata.name
    targets:
      - select:
          kind: ScheduledBackup
        fieldPaths:
          - spec.cluster.name

