apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

configMapGenerator:
  - name: recyclarr-config
    files:
      - config/recyclarr.yml

resources:
  - job.yaml
  - pvc.yaml
