apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-oidc-client-secret
    template:
      data:
        secret: "{{ .secret }}"
        secretHashed: "{{ .secretHashed }}"
  dataFrom:
    - extract:
        key: argocd-oidc-client-secret
